version: '3'
networks:
  bridge_network:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_postgres
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    networks:
      - bridge_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - "./sourcefiles/pgadmin:/var/lib/pgadmin"

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - bridge_network

    restart: unless-stopped
